### ISSUE TITLE
Error: Cannot find module '../../../config-schema/app.json'

### ISSUE THREAD

**Issue by irudoy** [zerobias/telegram-mtproto#84]
Error after updating to 3.2.0

```
Error: Cannot find module '../../../config-schema/app.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/(...)/node_modules/telegram-mtproto/lib/service/main/config-validation.js:19:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/(...)/node_modules/telegram-mtproto/lib/service/main/config-normalization.js:11:25)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/(...)/node_modules/telegram-mtproto/lib/service/main/init.js:16:28)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

**Comment by irudoy** [comment]
@zerobias

**Comment by zerobias** [comment]
@irudoy 
Oops, my fault, sorry
Add required files in 3.2.1

**Comment by irudoy** [comment]
TY
